package enums

type PhraseTrigger byte

const (
	PhraseNone PhraseTrigger = iota + 8
	PhraseOnAgony
	PhraseOnGoodWork
	PhraseOnEnemyGrenade
	PhraseOnFirstContact
	PhraseOnLostVisual
	PhraseOnFriendlyDown
	PhraseOnBeingHurt
	PhraseOnBeingHurtDissapoinment
	PhraseOnEnemyConversation
	PhraseOnEnemyDown
	PhraseOnEnemyShot
	PhraseOnOutOfAmmo
	PhraseOnRepeatedContact
	PhraseOnGrenade
	PhraseOnWeaponReload
	PhraseOnWeaponJammed
	PhraseOnWeaponMisfired
	PhraseOnDeath
	PhraseOnFight
	PhraseOnMutter
	PhraseOnBreath
	PhraseCoverMe
	PhraseFollowMe
	PhraseGetBack
	PhraseGoForward
	PhraseGogogo
	PhraseAttention
	PhraseHoldPosition
	PhraseGoLoot
	PhraseStop
	PhraseSilence
	PhraseOnYourOwn
	PhraseFire
	PhraseHoldFire
	PhraseSuppress
	PhraseSpreadout
	PhraseGetInCover
	PhraseKnifesOnly
	PhraseRegroup
	PhraseHandBroken
	PhraseLegBroken
	PhraseBleeding
	PhraseDehydrated
	PhraseExhausted
	PhraseHurtLight
	PhraseHurtMedium
	PhraseHurtHeavy
	PhraseHurtNearDeath
	PhraseDontKnow
	PhraseClear
	PhraseGoing
	PhraseCovering
	PhraseBadWork
	PhraseNegative
	PhraseReady
	PhraseOnPosition
	PhraseOnLoot
	PhraseGoodWork
	PhraseRoger
	PhraseRepeat
	PhraseLeftFlank
	PhraseScav
	PhraseSniperPhrase
	PhraseRightFlank
	PhraseInTheFront
	PhraseOnSix
	PhraseEnemyDown
	PhraseScavDown
	PhraseLostVisual
	PhraseEnemyHit
	PhraseKnifeKill
	PhraseNoisePhrase
	PhraseFriendlyFire
	PhraseRat
	PhraseDown
	PhraseHit
	PhraseNeedFrag
	PhraseNeedSniper
	PhraseNeedAmmo
	PhraseNeedHelp
	PhraseNeedWeapon
	PhraseNeedMedkit
	PhraseExitLocated
	PhraseLootKey
	PhraseLockedDoor
	PhraseLootBody
	PhraseLootContainer
	PhraseLootGeneric
	PhraseLootMoney
	PhraseLootWeapon
	PhraseCooperation
	PhraseLootNothing
	PhraseWeaponBroken
	PhraseOpenDoor
	PhraseCheckHim
	PhraseMumblePhrase
	PhraseUnderFire
	PhraseStartHeal
	PhraseToxic
)
